#!/bin/bash

# Quick Start Guide for Foundry Integration

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     AsbestosGuard - Foundry Agents Integration Ready          ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "STEP 1: Verify Configuration"
echo "  → Check .env.local has:"
echo "    • AZURE_AI_FOUNDRY_PROJECT_ENDPOINT=..."
echo "    • FOUNDRY_AGENT_1_ID=asst_WfzpVc2VFNSOimWtPFeH2M8A"
echo ""
echo "STEP 2: Azure Login"
echo "  → Run: az login"
echo ""
echo "STEP 3: Test Integration"
echo "  → Run: npm run test:foundry-analysis"
echo ""
echo "STEP 4: Start the App"
echo "  → Run: npm run dev"
echo "  → Navigate to Admin → Applications"
echo "  → Click any application"
echo "  → Click 'Run Analysis'"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✓ App is ready for Foundry integration!"
echo "✓ 'Run Analysis' now uses Foundry Agent1"
echo "✓ No Gemini API key required"
echo ""
echo "═══════════════════════════════════════════════════════════════"
