import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { ApplicationSummary } from '../../components/ApplicationSummary';
import { Badge } from '../../components/UI';
import { ArrowLeft, Calendar, User } from 'lucide-react';
const ApplicationDetail = ({ application, onBack }) => {
    return (_jsxs("div", { className: "max-w-4xl mx-auto px-4 py-8 sm:px-6 lg:px-8", children: [_jsxs("button", { onClick: onBack, className: "flex items-center text-slate-500 hover:text-slate-900 mb-6 transition-colors", children: [_jsx(ArrowLeft, { className: "w-4 h-4 mr-1" }), "Back to Dashboard"] }), _jsxs("div", { className: "bg-white rounded-lg shadow-sm border border-slate-200 p-6 mb-8", children: [_jsxs("div", { className: "flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 border-b border-slate-100 pb-6 mb-6", children: [_jsxs("div", { children: [_jsxs("div", { className: "text-sm text-slate-500 mb-1", children: ["Reference Number: ", application.id] }), _jsx("h1", { className: "text-2xl font-bold text-slate-900", children: application.companyName })] }), _jsx(Badge, { color: application.status === 'Approved' ? 'green' :
                                    application.status === 'Rejected' ? 'red' :
                                        application.status === 'Needs Information' ? 'yellow' : 'blue', children: application.status })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6 text-sm", children: [_jsxs("div", { className: "flex items-center", children: [_jsx(User, { className: "w-4 h-4 text-slate-400 mr-2" }), _jsx("span", { className: "text-slate-600 mr-2", children: "Applicant:" }), _jsx("span", { className: "font-medium text-slate-900", children: application.applicantName })] }), _jsxs("div", { className: "flex items-center", children: [_jsx(Calendar, { className: "w-4 h-4 text-slate-400 mr-2" }), _jsx("span", { className: "text-slate-600 mr-2", children: "Submitted:" }), _jsx("span", { className: "font-medium text-slate-900", children: application.submissionDate })] })] })] }), application.wizardData ? (_jsx(ApplicationSummary, { data: application.wizardData })) : (_jsx("div", { className: "bg-slate-50 p-8 rounded-lg text-center text-slate-500 border border-slate-200", children: _jsx("p", { children: "Detailed application data is not available for this legacy record." }) }))] }));
};
export default ApplicationDetail;
